// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2UP9CCxHVTws9JpzVHNAUto_8HGyiIa8',
    appId: '1:781681997781:web:581b5a60d22905424eaf5c',
    messagingSenderId: '781681997781',
    projectId: 'danassistant-d00bd',
    authDomain: 'danassistant-d00bd.firebaseapp.com',
    storageBucket: 'danassistant-d00bd.firebasestorage.app',
    measurementId: 'G-03CBS75NYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPrMGY6CX6IE3C3Un5x9YMsW8Fdq18mOo',
    appId: '1:781681997781:android:989962c8567eb7d64eaf5c',
    messagingSenderId: '781681997781',
    projectId: 'danassistant-d00bd',
    storageBucket: 'danassistant-d00bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxpjtpEQwK9xM5vNDW5y4Kom82rxmSezw',
    appId: '1:781681997781:ios:20eea7f6f401bbcf4eaf5c',
    messagingSenderId: '781681997781',
    projectId: 'danassistant-d00bd',
    storageBucket: 'danassistant-d00bd.firebasestorage.app',
    iosBundleId: 'com.example.taUiNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxpjtpEQwK9xM5vNDW5y4Kom82rxmSezw',
    appId: '1:781681997781:ios:20eea7f6f401bbcf4eaf5c',
    messagingSenderId: '781681997781',
    projectId: 'danassistant-d00bd',
    storageBucket: 'danassistant-d00bd.firebasestorage.app',
    iosBundleId: 'com.example.taUiNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2UP9CCxHVTws9JpzVHNAUto_8HGyiIa8',
    appId: '1:781681997781:web:9783f8ed403ee6e04eaf5c',
    messagingSenderId: '781681997781',
    projectId: 'danassistant-d00bd',
    authDomain: 'danassistant-d00bd.firebaseapp.com',
    storageBucket: 'danassistant-d00bd.firebasestorage.app',
    measurementId: 'G-8X7CGLGJX3',
  );

}